Repository Fakhatova/Rancid-Tomatillos, pull requests merged in 2021-08, with the labels that each got.

#1 Create pull_request_template.md
  .github/pull_request_template.md
Labels: enhancement

#29 Feature/react router
  package-lock.json
  package.json
  src/App.js
  src/MovieCard/MovieCard.js
  src/MovieDetails/MovieDetails.css
  src/MovieDetails/MovieDetails.js
  src/MovieList/MovieList.js
  src/Nav/Nav.js
  src/index.js
Labels: bug, enhancement, Iteration 4, Component, React Router

#32 Fix bug for home button url and h elemts
  cypress/integration/mainIndex_spec.js
  package-lock.json
  src/App.js
  src/Nav/Nav.js
Labels: Component, Cypress
